# This is a basic workflow to help you get started with Actions

name: Check year

# Controls when the action will run. 
on:
  push:    
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a web checker
        run: |
          chmod +x "${GITHUB_WORKSPACE}/check.sh"
          ${GITHUB_WORKSPACE}/check.sh
          echo "VAX_YEAR=$(${GITHUB_WORKSPACE}/check.sh)" >> $GITHUB_ENV
          echo "test"
          echo $VAX_YEAR
          
      - name: Send notification e-mail
        if: ${{env.VAX_YEAR}}!="1982"
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Vaccinaction ${{env.VAX_YEAR}}
          to: ewelina.w@gmail.com
          from: Me
